version: '3.8'

services:
  apache:
    # build: .
    image: php:apache
    container_name: myapps
    volumes:
      # - ./:/usr/local/apache2/htdocs/myapps
      - ./:/var/www/html/myapps
      # - D:/Wahid Prayogo/My-Apps/project-umat:/var/www/html/project-umat
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: wahid561
      DB_DATABASE: fa_addawah
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "561:80"
      - "443:443"
